### ISSUE TITLE
Http client timeout forces "panic: runtime error: invalid memory address or nil pointer dereference [recovered]"

### ISSUE THREAD

**Issue by arogovets** [neonxp/tamtam#3]
Ошибка воспроизводится на всех ваших примерах

Предполагаю, что из-за некорректной обработки ошибки вот здесь:
https://github.com/neonxp/tamtam/blob/ee63b08bd7861702123f9c5e83d60f49b1805e85/client.go#L42-L50

**Comment by neonxp** [comment]
Спасибо за ошибку, завтра днем все проверю и исправлю.

**Comment by neonxp** [comment]
Исправлено, спасибо!

**Comment by arogovets** [comment]
Спасибо!
